name = "sergiodxa"

# Update the compatibility date to the date you want to lock to
compatibility_date = "2024-10-11"

# This is needed for AsyncLocalStorage to work
compatibility_flags = ["nodejs_compat_v2"]

# Set the development port to be 3000
dev.port = 3000

kv_namespaces = [
  { binding = "cache", id = "597a3ce0108c42798aeac0044a566e31", preview_id = "cache" },
  { binding = "auth", id = "fda5fdfe90e74e2b82dd0ccd49346c27", preview_id = "auth@sergiodxa.com" },
  { binding = "redirects", id = "2bcc558cadce40dcb9c73f047c26be6c", preview_id = "redirects" },
]

r2_buckets = [
  { binding = "backups", bucket_name = "backups", preview_bucket_name = "backups" },
]

[[d1_databases]]
binding = "DB"
database_name = "db"
database_id = "f6bb2533-9284-4427-83e6-ea12c6630026"
migrations_dir = "./db/migrations"
