name = "sergiodxa"
compatibility_date = "2023-06-22"
node_compat = true

kv_namespaces = [
  { binding = "cache", id = "597a3ce0108c42798aeac0044a566e31", preview_id = "cache" },
  { binding = "auth", id = "fda5fdfe90e74e2b82dd0ccd49346c27", preview_id = "auth@sergiodxa.com" },
]

[[d1_databases]]
binding = "DB"
database_name = "db"
database_id = "f6bb2533-9284-4427-83e6-ea12c6630026"

# r2_buckets = [
#   { binding = "BUCKET", bucket_name = "campaigns", preview_bucket_name = "campaigns" }
# ]

# [[services]]
# binding = "SVG_GENERATOR"
# service = "svg-generator"
# environment = "production"

# [[services]]
# binding = "SVG_TO_PNG"
# service = "svg-to-png"
# environment = "production"
