name = "sergiodxa"
compatibility_date = "2023-06-22"

# kv_namespaces = [
#   { binding = "airtable", id = "7be9035dc2c04b2581e0a85ec1af46bb", preview_id = "airtable@sergiodxa.com" },
#   { binding = "cn", id = "8b961c1e81e1456aa045e11386648340", preview_id = "collectednotes@sergiodxa.com" },
#   { binding = "gh", id = "c24122b9e09e4ceda66f57797298db6b", preview_id = "github@sergiodxa.com" },
#   { binding = "auth", id = "fda5fdfe90e74e2b82dd0ccd49346c27", preview_id = "auth@sergiodxa.com" },
#   { binding = "tutorials", id = "35d8114ec66b41a3b1fb1723df61282f", preview_id = "tutorials@sergiodxa.com" },
# ]

# r2_buckets = [
#   { binding = "BUCKET", bucket_name = "campaigns", preview_bucket_name = "campaigns" }
# ]

# [[services]]
# binding = "SVG_GENERATOR"
# service = "svg-generator"
# environment = "production"

# [[services]]
# binding = "SVG_TO_PNG"
# service = "svg-to-png"
# environment = "production"
