name = "sergiodxa"
compatibility_date = "2023-06-22"
node_compat = true

kv_namespaces = [
  { binding = "cache", id = "597a3ce0108c42798aeac0044a566e31", preview_id = "cache" },
  { binding = "auth", id = "fda5fdfe90e74e2b82dd0ccd49346c27", preview_id = "auth@sergiodxa.com" },
  { binding = "redirects", id = "2bcc558cadce40dcb9c73f047c26be6c", preview_id = "redirects" },
]

r2_buckets = [
  { binding = "backups", bucket_name = "backups", preview_bucket_name = "backups" },
]

[[d1_databases]]
binding = "DB"
database_name = "db"
database_id = "f6bb2533-9284-4427-83e6-ea12c6630026"

# [[services]]
# binding = "SVG_GENERATOR"
# service = "svg-generator"
# environment = "production"

# [[services]]
# binding = "SVG_TO_PNG"
# service = "svg-to-png"
# environment = "production"
