-- Migration number: 0000 	 2023-12-21T16:41:15.770Z
CREATE TABLE users (
  id VARCHAR(255) UNIQUE PRIMARY KEY,
  displayName VARCHAR(255) NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  role VARCHAR(255) NOT NULL,
  -- Timestamps
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE connections (
  id VARCHAR(255) UNIQUE PRIMARY KEY,
  user_id VARCHAR(255) NOT NULL,
  provider_id VARCHAR(255) UNIQUE NOT NULL,
  provider_name VARCHAR(255) NOT NULL,
  -- Timestamps
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  -- Relations
  CONSTRAINT fk_connections_users FOREIGN KEY (user_id) REFERENCES users (id)
);
